---
name: Catalyst-Plugin-Log-Handler
version: 0.06
author:
  - Christoph Bussenius
abstract: Catalyst Plugin for Log::Handler
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor: 0
  Log::Handler: 0.32
  NEXT: 0
  Test::More: 0
provides:
  Catalyst::Plugin::Log::Handler:
    file: lib/Catalyst/Plugin/Log/Handler.pm
    version: 0.06
  Catalyst::Plugin::Log::Handler::Backend:
    file: lib/Catalyst/Plugin/Log/Handler.pm
no_index:
  directory: example
generated_by: Module::Build version 0.2807
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
